# Direct methods for solving linear systems (homework)


**Exercise 1.** Let us consider the linear system $A\mathbf{x} = \mathbf{b}$ where
$$
  A = 
  \begin{bmatrix}
  \epsilon & 1 & 2\\
  1 & 3 & 1 \\
  2 & 1 & 3 \\
  \end{bmatrix}.
$$

1. Find the range of values of $\epsilon \in \mathbb{R}$ such that the matrix $A$ is symmetric and positive definite.
**Suggestion**: use the *Sylvester's criterion* which states that  a symmetric matrix $A \in \mathbb{R}^{n \times n}$ is positive definite if and only if all the main minors (The main minors of $A \in \mathbb{R}^{n \times n}$ are the determinants of the submatrices $A_p = (a_{i,j})_{1 \leq i, j \leq p}$, $p = 1, ..., n$). of $A$ are positive.
2. What factorization is more suitable for solving the linear system $A\mathbf{x}=\mathbf{b}$ for the case $\epsilon=0$? Motivate the answer.
3. Compute the Cholesky factorization $A = R^T R$ for the case $\epsilon = 2$.
4. Given $\mathbf{b} = (1,1,1)^T$, solve the linear system by using the Cholesky factorization computed at the previous point.



**Exercise 2.** Let us consider the following matrix $A \in \mathbb R^{3 \times 3}$ depending on the parameter $\epsilon \in \mathbb R$:
$$
A =
\begin{bmatrix}
1 & \epsilon & -1 \\
\epsilon & \frac{35}3 & 1 \\
-1 & \epsilon & 2 \\
\end{bmatrix}.
$$



1. Calculate the values of the parameter $\epsilon \in \mathbb R$ for which the matrix $A$ is invertible (non singular).

2. Calculate the Gauss factorization $LU$ of the matrix $A$ (when non singular) for a generic value of the parameter $\epsilon \in \mathbb R$.

3. Calculate the values of the parameter $\epsilon \in \mathbb R$ for which the Gauss factorization $LU$ of the matrix $A$  (when non singular) exists and is unique.

4. Set $\epsilon = \sqrt{\frac{35}3}$ and use the pivoting technique to calculate the Gauss factorization $LU$ of the matrix $A$.

5. For $\epsilon=1$, the matrix $A$ is symmetric and positive definite. Calculate the corresponding Cholesky factorization of the matrix $A$, i.e. the upper triangular matrix with positive elements on the diagonal, say $R$, for which $A = R^T R$.

In [71]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [72]:
def get_A(ep):
    A = array([[1, ep, -1], [ep, 35/3, 1], [-1, ep, 2]])
    return A

In [73]:
eps = linspace(-15, 15, 10000)
for ep in eps:
    detA = linalg.det(get_A(ep))
    if(abs(detA) < 0.01):
        print("Ep: ", ep, " Det: ", detA)

Ep:  -2.3327332733273334  Det:  0.007199639855967358
Ep:  1.6666666666666643  Det:  2.565848768022582e-14


### Exercise 1 - Solution other numbers different to:

In [97]:
Singularity = [5/3,-7/3] 

In [17]:
from sympy import *
ep=Symbol("ep")
A = Matrix([[1, ep, -1], [ep, 35/3, 1], [-1, ep, 2]])

9

In [79]:
def LU_Mat_Sym(A_):
    A = A_.copy()
    N=sqrt(len(A))
    for k in range(N-1):   
        A[k+1:N-1,k] /= A_[k,k]
        for j in range(k+1,N):
            A[k+1:N-1,j] -= A_[k+1:N-1,k]*A_[k,j]
    
    L=tril(A)
    for i in range(N):
        L[i,i]=1.0
    U = triu(A)
    return L, U

def LU_Mat(A_):
    A = A_.copy()
    N=len(A)
    for k in range(N-1):   
        A[k+1:N-1,k] /= A_[k,k]
        for j in range(k+1,N):
            A[k+1:N-1,j] -= A_[k+1:N-1,k]*A_[k,j]
    
    L=tril(A)
    for i in range(N):
        L[i,i]=1.0
    U = triu(A)
    return L, U

In [39]:
A_generic = LU_Mat_Sym(A)

In [52]:
L = Matrix(A_generic[0])
U = Matrix(A_generic[1])

### Exercise 2 - Solution is:

In [54]:
L

Matrix([
[1.0,   0,   0],
[ ep, 1.0,   0],
[ -1,  ep, 1.0]])

In [50]:
U

Matrix([
[1,                       ep,     -1],
[0, 11.6666666666667 - ep**2, ep + 1],
[0,                        0,      2]])

### Exercise 3 - Uniqueness exists

In this case, the diagonal shall be different from 0. So, the values are all but $\epsilon = \mathbb R - \{\pm \sqrt{\frac{35}{3}}\}$

### Exercise 4 - $\epsilon = \sqrt{\frac{35}{3}}$

In [88]:
eps = sqrt(35/3)
A_eps = get_A(eps)
LU_eps = LU_Mat(A_eps)
A_eps

array([[ 1.        ,  3.41565026, -1.        ],
       [ 3.41565026, 11.66666667,  1.        ],
       [-1.        ,  3.41565026,  2.        ]])

In [87]:
# Result - U requires pivoting
L = LU_eps[0]
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 3.41565026,  1.        ,  0.        ],
       [-1.        ,  3.41565026,  1.        ]])

In [86]:
U = LU_eps[1]
U

array([[ 1.        ,  3.41565026, -1.        ],
       [ 0.        ,  0.        ,  4.41565026],
       [ 0.        ,  0.        ,  2.        ]])

In [89]:
# Using the following permutation matrix
P = array([[0, 1, 0],[1, 0, 0],[0, 0, 1]])

In [92]:
PA_eps = P.dot(A_eps)
PLU_eps = LU_Mat(PA_eps)
PLU_eps

(array([[ 1.        ,  0.        ,  0.        ],
        [ 0.29277002,  1.        ,  0.        ],
        [-1.        ,  3.41565026,  1.        ]]),
 array([[ 3.41565026, 11.66666667,  1.        ],
        [ 0.        , -8.25101641, -2.        ],
        [ 0.        ,  0.        ,  2.        ]]))

In [93]:
# Now, the result is:
L = PLU_eps[0]
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.29277002,  1.        ,  0.        ],
       [-1.        ,  3.41565026,  1.        ]])

In [94]:
U = PLU_eps[1]
U

array([[ 3.41565026, 11.66666667,  1.        ],
       [ 0.        , -8.25101641, -2.        ],
       [ 0.        ,  0.        ,  2.        ]])

In [95]:
P

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])